# Generated by Django 4.2.1 on 2026-05-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_applications', to='insuranceapp.customerprofile')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_applications', to='insuranceapp.insurance')),
            ],
            options={
                'verbose_name_plural': 'Customer Insurances',
                'unique_together': {('customer', 'insurance')},
            },
        ),
    ]
